project:
  type: book
  output-dir: docs

book:
  title: "GG501"
  author: Jason Venkiteswaran
  date: "2023-01-09"
  chapters: 
    - index.qmd
    - dataanalytic-visualization.qmd
    - dataanalytic-critique.qmd
    - data-to-decisions.qmd
    - assignments.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

