---
title: "Assignments"
---

## Assignment 1 - Exploratory Visualization in ggplot2

Your objective in this assignment is to select a dataset and do some exploratory analysis and visualization. You should select a dataset that interests you from [this online repository of datasets from various R packages](https://vincentarelbundock.github.io/Rdatasets/articles/data.html). The dataset you select should be different from other members of the class. Questions 1-4 should be completed with on selected dataset and question 5 should be completed with another dataset.

You have to structure your assignment as a RMarkdown file. Watch this video (\~45 mins) to learn how to start and navigate markdown files in R-Studio.

[You can use the following as a template](GG501_assignment_1_sample.Rmd) \[download to your working directory, and open in R-studio to edit/knit\] to get you started for your assignment.

Your assignment should answer the following questions and be totally reproducible. This means that you must read data in from a URL so that I can replicate your work, do not include any external data files in your submission, only submit one Rmd file.

### Questions

1.  Explain in a couple of sentences why you selected this dataset. \[2 marks\]

2.  Create a bar plot using `ggplot2`. Write a sentence interpreting what is happening in the graph. Make sure you read up on the documentation of the data to understand what is represented and how it was measured. \[5 marks\]

3.  Create a line or point plot using `ggplot2`. Write a sentence interpreting what is happening in the graph. Make sure you read up on the documentation of the data to understand what is represented and how it was measured. \[5 marks\]

4.  Create any other plot of your choosing using `ggplot2`. Write a sentence interpreting what is happening in the graph. Make sure you read up on the documentation of the data to understand what is represented and how it was measured. \[5 marks\]

5.  Select another dataset and tell a story with the data. Think about who a potential audience is for your story. Using the structure outlined in lecture slides, write a sentence or two for each phase of the data story: **Opening**, **Challenge**, **Action**, and **Resolution**. For each, include a visualization to illustrate (which may or may not be a graph of the data- external sources can be used here as well). In order to understand the context of the data, you will have to do some background research into the dataset this is generally available in the documentation. The story should include at least three graphs you create from the data(which must be labelled correctly and not be duplicates of graphs for questions 2-4). \[15 marks\]

6.  What might or could you have done differently in question 5 if you were preparing the analysis for another audience/user community? \[5 marks\]

### Submission

Submit via dropbox on mylearningspace by the end of February 1.

## Assignment 2 - Spatial and temporal visualization of urban data

Your objective in this assignment is to perform a real-world analysis of geospatial data from an urban centre. In this assignment you are taking on the role of an geospatial consultant tasked with analyzing aspects of the transportation system in a Canadian city that will be assigned to you. The specific exploration is up to you and to some extent will be a function of the available data, but feel free to do some background research.

-   A - Montreal

-   B - Vancouver

-   C - Toronto

-   D - Calgary

-   E - Winnipeg

-   other cities will be identified as necessary for other students.

Transportation issues are always top of mind in Canadian cities and you can choose to focus on aspects of the street network, availability of transit relative to population, actual commuting data, etc. It is up to you to define a reasonable question to explore and to source appropriate data for this assignment. Every city has an open data portal with some data that will likely be of help, however you can also seek data from other sources. I will be happy to help you with accessing datasets.

The outcome of this project is an Rmarkdown or Quarto report report detailing the issues explored (approximately 5 written pages double-spaced), the datasets, and the analysis performed. Visualization outputs should be presented in an appendix and an accompanying 10 minute presentation to be done in class on March 8th (we might do these via Zoom).

The assignment will be graded on the following criteria:

-   depth of analysis (25%)

-   visual aesthetics (25%)

-   reproducibility (10%)

-   analysis interpretation and accuracy (20%)

-   presentation (20%)

Recall some of the ideas about story-telling with data as you think through and put together your analysis and report.

### Submission

Submit the report (Rmarkdown or Quarto file plus PDF file) via dropbox on mylearningspace by the end of March 8. Presentations will take place that day as well.

## Assignment 3 - Tidy Tuesday Submission

For this assignment we will complete a **Tidy Tuesday submission**. Tidy Tuesday came out of the [R4DS (R for data science) Texbook and Online Learning Community](https://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund. A [second edition](https://r4ds.hadley.nz/) is currently being written. Every week a new data set (i.e., data are partly preprocessed but not completely tidy) alongside an article or a source is posted on the [Tidy Tuesday GitHub repository](https://github.com/rfordatascience/tidytuesday/tree/master/data).

The goal is to explore this data set using data wrangling and summarizing techniques and (a lot of) insightful visualizations. You will **only have around 24-48 hours** to create a visualization based on these data. If you use any external sources (e.g., other submissions) for ideas or as sources you must cite them, though you should strive to create a totally original visualization. You will need to submit code (R script) used to produce the visualization as well as an image file (JPG, PNG, or PDF) of the submission. The data are released on GitHub on Monday and your submission must be handed in by **end of day Wednesday, March 22** via dropbox on mylearningspace.

Participation in the Tidy Tuesday project may also serve to be an introduction to the wider R user community. There is a very active R user community on Twitter, [people livestream their R coding sessions on YouTube](https://www.youtube.com/watch?v=89l_3Y53qMM&ab_channel=DavidRobinson), and Tidy Tuesday submissions are typically shared on Twitter with the [#TidyTuesday hashtag](https://twitter.com/search?q=%23TidyTuesday). You are welcome to share your submission with the wider community after you submit it.

## Term Project (Analytics Demo)

Your task for a term project is to complete an independent data analysis project on a topic of your choosing. You must source your own dataset for this project. The project should address some clearly articulated questions and include enough contextual information about the problem in order to motivate your analysis.

You will create two outputs from your work:

1.  a written report and

2.  a class presentations (\~15 minutes) summarizing your work.

Your report should follow the following structure:

-   **Introduction (3-5 pages)** - outline the problem being explored with sufficient references and description of previous work. The end of the introduction section should highlight the objectives/questions being explored in the report.

-   **Data sources (2-3 pages)** - describe the data sources used for the analysis, how they were collected, sources of bias and/or data quality issues, etc. and any additional information that might impact how these data may or may not impact conclusions made from analysis.

-   **Data wrangling (2-3 pages)** - describe in general the methodology taken to acquire, clean, and prepare the data for analysis.

-   **Data analysis and visualization (4-5 pages)** - this section should describe the analyses undertaken to address the questions being explored.

    -   *Spatial* - your project should have an explicit spatial component - exploring spatial variation in your dataset. This may be maps but can also be spatial variables examined in novel ways.

    -   *Temporal* - your project should have an explicit temporal component - exploring temporal variation in your dataset.

-   **Interpretation (2-3 pages)** - interpret your analyses and visualization that are described in the above sections. This is your results section and should focus on understanding how your analyses adds understanding or new information to the questions outlined in the introduction.

-   **Discussion (2-3 pages)** - discuss limitations in your analysis, links to other papers or research that has been done, provide some ideas for where further work could be done to improve on the analysis completed in your report.

-   The length of the report should be between 4000 and 6000 words.

Your presentation will be done the last class, and should be no more than 12 minutes long. The structure of the presentation should mirror your report. The presentation file does not have to be submitted.
